version: '3.3'
services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'sampledb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'testuser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'testpassword'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3307'
      # Where our data will be persisted
    volumes:
      - ./sampledb-data:/var/lib/mysql
